### ISSUE TITLE
"Error: Must provide schema definition with query type or a type named Query."

### ISSUE THREAD

**Issue by gurdasnijor** [3VLINC/graphql-compiler#1]
When running this against a directory with `.graphql` files at arbitrary locations, I run into the following error:
`Error: Must provide schema definition with query type or a type named Query`

I've verified that there is a root type named `Query` present in one of the files as well.  Let me know if you need me to reproduce the issue and I'd be happy to help, thanks!

**Comment by danimbrogno** [comment]
Hm strange, a reproduction would definitely help. 

The issue is likely with the `graphql-code-generator` package that is used to actually do the conversion, but there could be a problem with the glob that this package passed in.

**Comment by iamdanthedev** [comment]
In order to solve this problem each file can have it's own:

```
extend type Query {

}
```

At least it helped me with another package :)
